[workspace]
members = ["./crates/*", "./native", "./xtask", "./examples/rust/*"]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/storycraft/asdf-overlay"

[workspace.dependencies]
asdf-overlay = { path = "./crates/overlay" }
asdf-overlay-client = { path = "./crates/client" }
asdf-overlay-common = { path = "./crates/common" }

tokio = "1.44.2"

[workspace.dependencies.dll-syringe]
git = "https://github.com/fry/dll-syringe"
rev = "0a8b18e"
default-features = false