[package]
name = "asdf-overlay-client"
description = "Asdf Overlay Injector & Client"
version.workspace = true
edition.workspace = true
license.workspace = true
authors = ["storycraft <storycraft@pancake.sh>"]

[dependencies]
asdf-overlay-common = { workspace = true }
tokio = { workspace = true }

anyhow = "1.0.97"
futures = "0.3.31"

[dependencies.dll-syringe]
git = "https://github.com/fry/dll-syringe"
rev = "0a8b18e"
default-features = false
features = ["into-x86-from-x64", "syringe", "rpc-raw"]

[dev-dependencies]
asdf-overlay = { workspace = true }
tokio = { workspace = true, features = ["full"] }
rand = "0.9.0"
