[package]
name = "asdf-overlay-client"
description = "Asdf Overlay Injector & Client"
version.workspace = true
edition.workspace = true
license.workspace = true
authors = ["storycraft <storycraft@pancake.sh>"]

[dependencies]
asdf-overlay-common = { workspace = true }
tokio = { workspace = true }

dll-syringe = { version = "0.15.2", default-features = false, features = ["into-x86-from-x64", "syringe", "rpc-raw"] }
anyhow = "1.0.97"
futures = "0.3.31"

[dev-dependencies]
asdf-overlay = { workspace = true }
tokio = { workspace = true, features = ["full"] }
rand = "0.9.0"
