[package]
name = "asdf-overlay-client"
description = "Asdf Overlay Injector & Client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors = ["storycraft <storycraft@pancake.sh>"]

[dependencies]
asdf-overlay-common = { workspace = true }
tokio = { workspace = true, features = ["macros", "time"] }

anyhow = "1.0.97"
dll-syringe = { workspace = true, features = [
    "into-x86-from-x64",
    "syringe",
    "rpc-payload",
] }

[dev-dependencies]
asdf-overlay = { workspace = true }
tokio = { workspace = true, features = ["full"] }
rand = "0.9.0"
