name: deploy

concurrency: production

on:
  workflow_dispatch:
    inputs:
      level:
        type: choice
        description: Bump level
        options:
          - major
          - minor
          - patch

jobs:
  publish:
    runs-on: windows-latest
    environment: publish
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup cd
        run: |
          git config user.name 'Asdf Overlay Continuous Deployment'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Setup rust
        uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - name: install cargo-release
        run: cargo install cargo-release

      - name: bump cargo package versions, publish
        run: |
          cargo release 0.1.0 \
          --workspace \
          --no-confirm \
          --execute
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - name: release
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: 'v0.1.0',
              target_commitish: '${{ github.ref }}',
              name: 'Asdf Overlay v0.1.0',
              draft: false,
              generate_release_notes: true
            })
            return data.id
