name: publish

concurrency: production

on:
  workflow_dispatch:
    inputs:
      level:
        type: choice
        description: Bump level
        options:
          - major
          - minor
          - patch
      execute:
        type: boolean
        description: Actually publish (not dry run)

jobs:
  release-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      signing-policy: ${{ inputs.execute == 'true' && 'release-signing' || 'test-signing' }}

  publish:
    runs-on: windows-latest
    environment: publish
    needs: release-deploy
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup cd
        run: |
          git config user.name 'Asdf Overlay Continuous Deployment'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Setup rust
        uses: dtolnay/rust-toolchain@nightly

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: 'deploy'
          cache-on-failure: true
          cache-all-crates: true

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Set node dry run
        if: ${{ inputs.execute == 'false' }}
        run: npm config set dry-run=true

      - name: Bump node package version
        id: bump
        run: |
          npm config set git-tag-version=false
          $ver = npm version ${{ github.event.inputs.level }}
          git commit -a -m "chore: Bump node package version"
          "version=" + $ver.substring(1) >> $env:GITHUB_OUTPUT

      - name: Bump cargo package versions, publish
        run: cargo release ${{ steps.bump.outputs.version }} --workspace --no-confirm --no-verify ${{ inputs.execute == 'true' && '--execute' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - name: Run build script
        run: npm run ci:build

      - name: Download signed artifacts
        uses: actions/download-artifact@v4
        with:
          artifact-ids: ${{ needs.release-deploy.outputs.signed-artifact-id }}
          path: 'target/out-signed-artifact'

      - name: Use signed artifacts
        run: Copy-Item -Path "target\out-signed-artifact\*" -Force

      - name: Publish node package
        run: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release
        if: ${{ inputs.execute == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          name: 'Asdf Overlay v${{ steps.bump.outputs.version }}'
          draft: false
          generate_release_notes: true
          make_latest: true
          tag_name: "v${{ steps.bump.outputs.version }}"
          target_commitish: '${{ github.ref }}'
          files: |
            asdf_overlay-aarch64.dll
            asdf_overlay-x86.dll
            asdf_overlay-x64.dll
