on:
  workflow_dispatch:
  push:
    branches: 'dev'
    paths:
      - '**.rs'

name: rustfmt-push
jobs:
  format:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
            components: rustfmt
      - uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
